name: device_media_finder
description: "A Flutter plugin for accessing media files (videos and audio) on the device with support for various formats and thumbnails."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/device_media_finder"

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.device_media_finder
        pluginClass: DeviceMediaFinderPlugin
      ios:
        pluginClass: DeviceMediaFinderPlugin

  #

